server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://test.cnqa80wgmamz.us-east-1.rds.amazonaws.com:3306/test
    username: test
    password: test12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  jap:
    database: mysql
    generate-ddl: true
    show-sql: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

cloud:
  aws:
    s3:
      bucket: s3testsm
    stack.auto: false
    region.static: us-east-1
    credentials:
      accessKey: AKIAXYKJRRKF2FGZ3T4F
      secretKey: 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